name: release
on:
  push:
    branches:
      - master
jobs:

  build:
      name: build-package
      runs-on: ubuntu-latest
      steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v1
        with:
            node-version: '14'
      - name: Restore npm packages
        run: npm install
      - name: Install Angular
        run: npm install -g @angular/cli
      - name: Build package
        run: npm run build:lib
      - name: Publish if version has been updated
        if: github.ref == 'refs/heads/master'
        uses: pascalgn/npm-publish-action@1.3.9
        with: 
          tag_name: "v%s"
          tag_message: "v%s"
          create_tag: "true"
          commit_pattern: "^chore\\(release\\): (\\S+)"
          workspace: "./@packaged/angular-star-rating"
          publish_command: "yarn"
          publish_args: "--non-interactive"
        env: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
          NPM_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }} 

